### ISSUE TITLE
Cannot get parsed ast correctly in production

### ISSUE THREAD

**Issue by lhz516** [federicobond/solidity-parser-antlr#103]
In development, `parser.parse(code)` returns the correct value
![image](https://user-images.githubusercontent.com/9879279/78110683-48bcea00-73b0-11ea-9f91-9fb6fa324e2d.png)

but in production, it returns `{type: "p"}` which doesn't make any sense. I built it with `vue-cli`

![image](https://user-images.githubusercontent.com/9879279/78110700-4fe3f800-73b0-11ea-8529-7ad1db635032.png)

Do you have any ideas?

**Comment by lhz516** [comment]
I did some investigation and found it's because my webpack changed variable names and it caused the constructor name changed.
![image](https://user-images.githubusercontent.com/9879279/78112718-78212600-73b3-11ea-8eab-e76b075b75c6.png)

I'm wondering if there's any better way to get `ctx.constructor.name` here:

https://github.com/federicobond/solidity-parser-antlr/blob/ca5da9b0d11c96c6d79d7fbe3a817a0bce6ce656/src/ASTBuilder.js#L1231

**Comment by Janther** [comment]
If you are using `terser-webpack-plugin` I suggest keeping function names.

```Javascript
new TerserPlugin({
  terserOptions: {
    mangle: {
      keep_fnames: true
    }
  }
})
```

**Comment by Janther** [comment]
Having said that, the fact that this plugin is so dependant on the function names to be left alone is an issue, but I'm unsure how much work it'll be needed to refactor this.

**Comment by lhz516** [comment]
Overwriting `terserOptions` resolved the issue. However, the bundle size increased.

Anyways, it's not blocking me anymore. Thanks!
