### ISSUE TITLE
Information loss in BinaryOperation when both sides are TupleExpression

### ISSUE THREAD

**Issue by duaraghav8** [federicobond/solidity-parser-antlr#14]
code:
```
contract A {
    
    function baz(){
        uint foo;
        uint bar;
        
        (foo,  , ,,  bar,) = (1,2,3,4,5,6);
    }
}
```
```
> const ast = sp.parse(code);
> const expression = ast.children[0].subNodes[0].body.statements[1].expression
```

In above scenario, accessing the node `expression.left` gives info about `foo` & `bar` as 2 array items.
The problem is that after parsing, we loose the comma info in the tuple and therefore the ability to map the Identifier with its corresponding value.

Is there a work-around for this (I'm trying to avoid using my custom RegExp on the code string)?

(I'm not sure if this is a problem within the scope of a parser to solve, but it just feels like this information should be present).

**Comment by federicobond** [comment]
Yes! Sorry about that, I should replace each missing array element with a null in the resulting AST. I'll push a fix soon.

**Comment by duaraghav8** [comment]
```
(,,foo,  , ,,  bar,,) = (1,2,3,4,5,6);
```

in above case, `expression.left`:

```
{ type: 'TupleExpression',
  elements:
   [ null,
     { type: 'Identifier', name: 'foo' },
     null,
     null,
     null,
     { type: 'Identifier', name: 'bar' },
     null ],
  isArray: false }
```

@federicobond  I think the middle ones are being generated fine, but the `null`s on the extremes accumulate all the commas into a single null. There should've been 2 `null`s at start & end if you see how the commas are placed in the code.

**Comment by federicobond** [comment]
Good catch. What about now?

**Comment by federicobond** [comment]
Wait, no, I made another mistake.

**Comment by federicobond** [comment]
OK, should be working.

**Comment by duaraghav8** [comment]
ah yes not it does, thanks!
