### ISSUE TITLE
incorrectly parses abstract func whose name is at the end

### ISSUE THREAD

**Issue by duaraghav8** [federicobond/solidity-parser-antlr#16]
```
contract Foo {
    function(address) external returns (address) myFunc;
}
```
This code compiles (notice that the function's name is right before semicolon).

Unfortunately I haven't been able to find any literature on the exact rules the compiler follows in this situation. Couldn't find anything helpful in the [solidity grammar](https://github.com/ethereum/solidity/blob/develop/docs/grammar.txt) either.

(This pattern is not used very often, so not a big problem IMO)

**Comment by federicobond** [comment]
Hey! Sorry for the delay. The code you posted is a state variable of function type. This should no longer be an issue with the latest published version, please reopen if that's not the case.

**Comment by duaraghav8** [comment]
ah yes, I only [very recently realised](https://github.com/ethereum/solidity/issues/3423) this myself, thanks!
