### ISSUE TITLE
Ability to parse NatSpec comments

### ISSUE THREAD

**Issue by chmanie** [federicobond/solidity-parser-antlr#20]
First of all thanks for creating this fine tool. It's been helping us a lot already!

In our effort to generate documentation from [Ethereum NatSpec comments](https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format) I decided to take a crack at adding the ability to parse those to this tool. I have to admit I am quite new to Antlr and for quite some time it felt like I was just messing around with it. But I got to a state where I am able to successfully parse single line and multiline NatSpec comments and add them to the AST. That didn't come without any caveats though:

- Quotes (single or double) break the parsing (it just won't pick it up)
- The regex used to pick up multiline comments is just embarrassingly simple (it will just ignore any comments without an `@` in them)
- Also there definitely must be some room for improvement and/or simplification in both the grammar and the AST builder

These are things I couldn't figure out yet (also sadly due to the sparse JS runtime documentation) and if this is a thing you might want to include I'd highly appreciate a little push in the correct direction.

Here's my attempt so far:

The antlr grammar:
https://github.com/solidityj/solidity-antlr4/compare/master...chmanie:feature/add-natspec

The AST builder:
https://github.com/federicobond/solidity-parser-antlr/compare/master...chmanie:feature/add-natspec

**Comment by federicobond** [comment]
Awesome @chmanie! Can you open a pull request so I can review and merge the changes? Also, please take a look at this (now deprecated) version that the team at Zeppelin did, and let me know if there are some good ideas to take from there.

https://github.com/OpenZeppelin/solidity-docgen/blob/dcb637ecfac2a7a4cd2e2ede0a3e55bd4c6c8841/parser/grammar/Solidity.g4

**Comment by federicobond** [comment]
Can we open the grammar to accept any identifier in place of a predefined set of keywords for NatSpec specifiers?

**Comment by chmanie** [comment]
Hey @federicobond! Thanks for checking in. The link to the grammar by OpenZeppelin seems really helpful (it looks like they could solve at least some of the troubles I've had). Will look into that and open PRs once I incorporated some of their ideas.

> Can we open the grammar to accept any identifier in place of a predefined set of keywords for NatSpec specifiers?

Seems reasonable. I'll do that!

**Comment by federicobond** [comment]
Hi @chmanie! Did you have time to look into it? Would love to see this implemented.

**Comment by chmanie** [comment]
I haven't had time lately. This turned into a bigger priority for us now, so I'll probably work on that in the next few days.

**Comment by federicobond** [comment]
Hi @chmanie, this is starting to become more of a priority for me too. Are you still working on it?

**Comment by 0Alic** [comment]
Hi, is this issue still open?
It would be very interesting

**Comment by chmanie** [comment]
I'm sorry, I currently don't have the time to actively work on this.

**Comment by 0Alic** [comment]
No worry, thanks for the answer!

**Comment by obernardovieira** [comment]
I see it's related to #10 
Is this still open? I'm also interested. I had a look at the .g4 file and there's something there about the natspec. Is it working?
I started my own parser, but this approach is much smarter.

**Comment by federicobond** [comment]
Yes, it's still open. Ideally, we would be able to attach a NatSpec key to AST nodes that have one, with all the properties already parsed.

**Comment by obernardovieira** [comment]
So, can I open a PR with @chmanie's code and try to make it work?

**Comment by federicobond** [comment]
Sure! Go ahead.

**Comment by ryanchristo** [comment]
Hey there @obernardovieira and @federicobond!

I wrote a script to parse natspec comments in one of our projects:
https://github.com/JoinColony/colonyNetwork/blob/develop/scripts/docgen.js

It's specific to our project at the moment but it might help with some ideas.

**Comment by obernardovieira** [comment]
Hello @ryanchristo thank you.
I think the PR is now finished. Have a look, please.
