### ISSUE TITLE
Allow multiple variables to be declared as the part of the tuple statement

### ISSUE THREAD

**Issue by LogvinovLeon** [federicobond/solidity-parser-antlr#23]
Solidity version [0.4.24](https://github.com/ethereum/solidity/blob/develop/Changelog.md#0424-2018-05-16) introduced this syntax:
```solidity
(uint256 a, bytes memory b) = f();
```

Parser currently doesn't support it.
```
no viable alternative at input '(uint256a'. mismatched input ',' expecting {';', '='}. extraneous input ')' expecting {';', '='}
```

**Comment by federicobond** [comment]
Thank you, this is now fixed in master. I will push an update tomorrow.

**Comment by federicobond** [comment]
`0.2.12` has just been published in npm. Let me know if you find any other issues.

**Comment by LogvinovLeon** [comment]
Thanks! That was fast!
