### ISSUE TITLE
Parsing errors

### ISSUE THREAD

**Issue by alcuadrado** [federicobond/solidity-parser-antlr#24]
Hi Fede,

I'm opening this issue to track the different parsing errors which I found when creating [this PR](https://github.com/federicobond/solidity-extract-imports/pull/5).

These files can't be parsed:

* https://github.com/0xProject/0x-monorepo/blob/bc0ae6be318a15bf8670a6da9a59d9bdb12cadae/packages/contracts/src/contracts/current/protocol/AssetProxy/ERC20Proxy.sol
* https://github.com/0xProject/0x-monorepo/blob/bc0ae6be318a15bf8670a6da9a59d9bdb12cadae/packages/contracts/src/contracts/current/protocol/AssetProxy/ERC721Proxy.sol

**Comment by federicobond** [comment]
Thanks! This is related to the recently introduced multi variable definition statements. It has been fixed in master. I will publish an update soon.
