### ISSUE TITLE
Error parsing decimal

### ISSUE THREAD

**Issue by golivax** [federicobond/solidity-parser-antlr#33]
Hi Federico. I'm trying to parse a solidity file and I'm getting an error at the following line:

`minContribution = .1 ether;`

From what I could dig, I think this statement violates the DecimalNumber element of the grammar, as it needs to start with a number ([0-9]+):

```
DecimalNumber
  : [0-9]+ ( '.' [0-9]* )? ( [eE] [0-9]+ )? ;
```
This statement is part of the source code of a contract running on Ethereum (https://etherscan.io/address/0x009ef15c147ff4c0eb373e1abd2f4d184e5cb916#code), which makes me think that the .X decimal format is valid syntax. However, I'm a total newbie in Solidy, so I could be very wrong. 

Thoughts on this? Thanks!

**Comment by federicobond** [comment]
Yes, this was a known issue to me for some time. Thanks for bringing it up!

I will push an update shortly, stay tuned.
