### ISSUE TITLE
Error parsing return statement

### ISSUE THREAD

**Issue by golivax** [federicobond/solidity-parser-antlr#34]
Hi Federico. I noticed the parser throws an error when parsing a return statement written like this "return();". Again, I've seen contracts running on Ethereum that use this statement, so I think it's syntactically valid. But again, I'm a newbie in Solidity, so I might be wrong. Would you mind looking into this? Thanks!

**Comment by federicobond** [comment]
Indeed, even if it's horrible style, it's apparently syntactically valid. I have fixed this in https://github.com/federicobond/solidity-parser-antlr/commit/be35e6830f3019f58e48a6c441c0da23fd1136f2 and will include it in the next release.

**Comment by golivax** [comment]
Awesome, tks!

**Comment by federicobond** [comment]
Thanks for reporting @golivax!
