### ISSUE TITLE
How to implement this for Vyper?

### ISSUE THREAD

**Issue by maurelian** [federicobond/solidity-parser-antlr#35]
Hi @federicobond!

I'm interested in replicating this lib for vyper. These are the steps I think that would require, would appreciate if you can point out any big pieces I'm missing, or pitfalls I might not be seeing?

1. Create a similar [g4 file](https://github.com/solidityj/solidity-antlr4/blob/master/Solidity.g4) based on the vyper grammar (this is probably the hardest part)
2. Change the [test input](https://github.com/solidityj/solidity-antlr4/blob/master/test.sol) to vyper code
3. Customize much of the [parser source](https://github.com/federicobond/solidity-parser-antlr/tree/master/src) to work with vyper. 
4. Update tests for this lib. 

Thanks again for maintaining this awesome lib.

**Comment by federicobond** [comment]
No, that’s pretty much it. There are also the unit tests which assert more fine-grained components of the parser.

I suggest you use the ANTLR plugin for IntelliJ IDEA to test and debug the grammar before moving to the JavaScript AST building part.

**Comment by maurelian** [comment]
Amazing, thanks!
