### ISSUE TITLE
Error parsing function modifiers.

### ISSUE THREAD

**Issue by MKmknd** [federicobond/solidity-parser-antlr#38]
Hi Federico.

Thank you for creating this awesome tool! It’s been helping me a lot.

When I tried to parse a contract like the following, the parser parsed the code including an error:

```
contract Owned is temp {    
    modifier onlyOwner {
        assert(msg.sender == owner);
        _
    }
}
```

```
  "errors": [
    {
      "message": "no viable alternative at input '_}'",
      "line": 5,
      "column": 4
    }
  ]
```

This error is occurred because of underscore (indeed, if we remove the underscore, the parser would not report the error).
The underscore is a part of the source code of a contract running on Ethereum (a function modifier).

Thoughts on this? Thank you!

**Comment by federicobond** [comment]
Hi @MKmknd, the parser is failing because you are missing a semicolon after the underscore placeholder.

**Comment by MKmknd** [comment]
Thank you for the reply. You are right.
I checked the release note. Then I found that after version 0.4.0, we need to add semicolon after underscore...
Thank you very much!!
