### ISSUE TITLE
`abi.decode(b, (uint256[]))` breaks parser.

### ISSUE THREAD

**Issue by maxsam4** [federicobond/solidity-parser-antlr#50]
`a = abi.decode(b, (uint256[]));` breaks the parser.

Any array inside the tupple breaks the parser. It is valid solidity code though.

Full sample code
```
pragma solidity ^0.5.0;
contract hello {
    function world(bytes memory b) public {
        uint256[] memory a;
        a = abi.decode(b, (uint256[]));
    }
}
```

**Comment by federicobond** [comment]
Thanks for reporting this! I just pushed a fix to `master`. Can you try it out and let me know if it works for you?

**Comment by maxsam4** [comment]
Thanks for the quick fix. It is working as expected now.
