### ISSUE TITLE
bug: line comment cannot be parsed

### ISSUE THREAD

**Issue by yxliang01** [federicobond/solidity-parser-antlr#54]
Give a very simple example, if I add a `//` followed by a newline to a correctly written contract, current version gives `ParseError` with message `extraneous input \'/\' expecting {<EOF>, \'pragma\', \'import\', \'contract\', \'interface\', \'library\'} (1:0)`. This happens regardless where the comment is put.

**Comment by federicobond** [comment]
Hi @yxliang01, can you provide a complete code example that fails? I could not reproduce this.

**Comment by yxliang01** [comment]
@federicobond As requested:
```sol
//
contract SmallTest {
    uint256 public x;
    bool yes = false;
    
    constructor () public {
        x = 10;
    }
    
    function getX(uint256 a) public returns(uint256) {
        if (yes == true)
            return x  + 1;
        else
            return x + 2;
    }
}
```

**Comment by yxliang01** [comment]
In contrast, the following can be parsed successfully.

```solidity
/**/
contract SmallTest {
    uint256 public x;
    bool yes = false;
    
    constructor () public {
        x = 10;
    }
    
    function getX(uint256 a) public returns(uint256) {
        if (yes == true)
            return x  + 1;
        else
            return x + 2;
    }
}
```

**Comment by federicobond** [comment]
Sorry, I am still unable to reproduce it :(

Can you provide an full example similar to this one that fails?
https://runkit.com/federicobond/test-parser

**Comment by yxliang01** [comment]
Hmm sorry that after debugging, I realized that the file content in memory has `//` all replaces with `/`. Looks like it has something to do with the inter-component communication of my system. Sorry for the false bug report. @federicobond

**Comment by federicobond** [comment]
No worries.
