### ISSUE TITLE
UserDefinedTypeName needs to be address payable

### ISSUE THREAD

**Issue by TimDaub** [federicobond/solidity-parser-antlr#55]
My contract has the following constructor

```solidity
import "./Negotiator.sol";

constructor(Negotiator _negotiator) public {
        owner = msg.sender;
        negotiator = _negotiator;
}

function() public payable {
  revert("Cannot send ether");
}
```

I'd like to use `web3.eth.abi.encodeParameters` to encode my constructor parameters.
With solidity-parser-antlr, I'm getting the following result for my contract's constructor parameters however:

```json
[ { type: 'Parameter',
    typeName: { type: 'UserDefinedTypeName', namePath: 'Negotiator' },
    name: '_negotiator',
    storageLocation: null,
    isStateVar: false,
    isIndexed: false } ]
```

The solidity documentation states that when a fallback function is available on the contract, then the Contract Type should be converted to an `address payable`.

**Comment by federicobond** [comment]
Hi Tim, the process of getting the actual type behind a type name is called type resolution. To resolve types in your case you would need to find any imports, parse those files into ASTs and then go looking for contracts/interfaces matching the names you want to resolve. Then include the `payable` qualifier if there is a fallback function in that contract.

You would need to perform this pass before your calls to `web3.eth.abi.encodeParameters`.

**Comment by federicobond** [comment]
Check this out and let me know if this works for you: [solidity-type-resolver](https://github.com/federicobond/solidity-type-resolver)
