### ISSUE TITLE
Returning only contract and params (no func) when calling it in another method

### ISSUE THREAD

**Issue by obernardovieira** [federicobond/solidity-parser-antlr#57]
Hi,
Sorry If I was not clear with the title, I don't know how to explain the problem, TBH.

So, going directly into the problem, this https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC721/ERC721.sol#L273 using the code below, returns the result shown in the end. I was looking at the solidity-antlr4 repository and it seems to not be catching that use case and in fact, it's just missed. Am I right?
```javascript
parser.visit(fLink, {
    FunctionCall: (functionCallNode) => {
        if (functionCallNode.expression.name === 'IERC721Receiver') {
            console.log(functionCallNode);
        }
    },
});
```
```bash
{ type: 'FunctionCall',
  expression: { type: 'Identifier', name: 'IERC721Receiver' },
  arguments: [ { type: 'Identifier', name: 'to' } ],
  names: [] }
```

Cheers

**Comment by federicobond** [comment]
HI @obernardovieira, without looking at the whole AST it's hard to know what's going on. I think you should see a parent node FunctionCall with name `onERC721Received` that takes that function call as expression, but I could be wrong. Let me know if that helps.

**Comment by obernardovieira** [comment]
Hi @federicobond thanks for the quick answer, and thanks for this package btw.
You right, I was not clear.
So I put everything together and I realized I was doing one thing wrong, which was `fDef.body.statements.forEach((fLink) => {` because I actually don't need it, so I removed and updated `parser.visit(fLink, {` to `parser.visit(fDef, {` and it actually catches *IERC721Receiver* again.
```javascript
parser.visit(ast, {
    FunctionDefinition: (fDef) => {
        fDef.body.statements.forEach((fLink) => {
            parser.visit(fLink, {
                FunctionCall: (functionCallNode) => {
                    if (functionCallNode.expression.name === 'IERC721Receiver') {
                        console.log(functionCallNode);
                    }
                },
            });
        });
    },
});
```
What I want to do here it to map the function being called in a function's body. And *ast* is the complete file.

**Comment by federicobond** [comment]
Not sure I understand you correctly. Examining the full contract AST in the console should help you understand where to look for. If the piece you are looking for it's not there, please describe the AST output you are getting and what you would have expected to see.

**Comment by obernardovieira** [comment]
Hi, I can confirm, I missing one thing. Thanks.
On the other hand, the ConstructorDefinition returns nothing and the constructor is actually returned as FunctionDefinition with an "isConstructor" variable as true. Is it a known problem?

**Comment by federicobond** [comment]
Where did you see this ConstructorDefinition?

**Comment by obernardovieira** [comment]
Well, here https://github.com/solidityj/solidity-antlr4/blob/edce5c44d2d681e32bb23034d822bf0fcf1cb43e/Solidity.g4#L65

**Comment by federicobond** [comment]
Ahh right, AST names are different from ANTLR parser rules. You can have a `function MyContract {}` which would be a FunctionDefinition according to ANTLR but is another form of constructor.

**Comment by obernardovieira** [comment]
I know, but what about `constructor() {}`? How can I catch it?

**Comment by federicobond** [comment]
The node for function `MyContract {}` has a `name` key with "MyContract" as value, whereas in `constructor() {}`, `name` is null.

Please try different sources and review the full generated AST. You should be able to get most of your answers from there.
