### ISSUE TITLE
Errors on parameters with storage or memory location

### ISSUE THREAD

**Issue by cgewecke** [federicobond/solidity-parser-antlr#6]
From aragon-core [here](https://github.com/aragon/aragon-core/blob/master/contracts/apps/basic-governance/VotingApp.sol#L143)
```
function transitionToVotingState(Vote storage vote) internal {
    vote.state = VoteState.Voting;
    OwnershipApp ownershipApp = getOwnershipApp();
    etc. . .
```
Error is:
```
"message": "mismatched input 'storage' expecting {',', ')'}",
```

Possible fix at [this rule](https://github.com/federicobond/solidity-parser-antlr/blob/master/Solidity.g4#L83), and it's management [here](https://github.com/federicobond/solidity-parser-antlr/blob/master/src/ASTBuilder.js#L612-L633)?

Federico, I don't want to hound you with PRs of questionable quality over here but as you know, I'm also perfectly happy to submit them. Somewhat curious about how this parser works. Whatever is easiest, though.

**Comment by federicobond** [comment]
Fixed in a720198d59eda8c9b496ba76e98b3c7846ab62bc.
