### ISSUE TITLE
MemberAccess does not return parameters

### ISSUE THREAD

**Issue by obernardovieira** [federicobond/solidity-parser-antlr#62]
According to https://solidity.readthedocs.io/en/v0.5.8/contracts.html#libraries we can call a library method like `Set.insert(knownValues, value)`. We may want to call something like `Set.calculate(value1, value2)`, which would return another value.

The problem is, solidity-parser-antlr is returning this as a `MemberAccess`, which is correct, but then it does not give the parameters.
It does appear when using FunctionCall, but only under an expression of type `MemberAccess`.

I could make a workaround but it could also be interesting to get the parameters. Will it be possible?

**EDIT**
Same happens with `super._transferFrom(from, to, tokenId);`

**Comment by federicobond** [comment]
Hi @obernardovieira just checked your example and the output looks correct. The expression from your first example looks like this:

````javascript
{
  "arguments": [
    {
      "name": "knownValues"
      "type": "Identifier"
    }
    {
      "name": "value"
      "type": "Identifier"
    }
  ]
  "expression": {
    "expression": {
      "name": "Set"
      "type": "Identifier"
    }
    "memberName": "insert"
    "type": "MemberAccess"
  }
  "names": []
  "type": "FunctionCall"
}
````

It's a function call whose target expression is a MemberAccess for the member `insert` of the expression `Set`. The information of the parameters is available in the arguments key of the FunctionCall node.

**Comment by obernardovieira** [comment]
:man_facepalming: you right. I misunderstood the result. Sorry.

**Comment by federicobond** [comment]
No worries.
