### ISSUE TITLE
Add support for modifier-style constructor calls

### ISSUE THREAD

**Issue by Janther** [federicobond/solidity-parser-antlr#67]
The modifiers constructor calls don't have any difference with modifier calls in the `ModifierInvocation` AST node.

```JSON
// Constructor Call Modifier
{
  "type": "ModifierInvocation",
  "name": "Ownable",
  "arguments": [],
  "loc": [Object],
  "range": [Array]
}

// Normal Modifier
{
  "type": "ModifierInvocation",
  "name": "onlyOwner",
  "arguments": [],
  "loc": [Object],
  "range": [Array]
}
```

I would suggest adding an attribute `isConstructorCall` similar to `isConstructor` in `FunctionDefinition`

**Comment by federicobond** [comment]
Hi @Janther, thanks for the suggestion! Unfortunately, I don’t see a way of distinguishing between the two without doing some form of name resolution, which is out of the scope of this PR. As far as syntax goes, Solidity made no difference between those two cases, so you would need to process the AST and annotate it with your extra information if you want to do it.

**Comment by Janther** [comment]
the problem I'm facing in prettier-solidity is that:
```Solidity
contract ERC721FullMock is ERC721Mintable, ERC721Full {
    constructor (string memory name, string memory symbol) public ERC721Mintable() ERC721Full(name, symbol) {}
}
```

is processed as 
```Solidity
contract ERC721FullMock is ERC721Mintable, ERC721Full {
    constructor (string memory name, string memory symbol)
        public
        ERC721Mintable
        ERC721Full(name, symbol)
    {}
}
```
by prettier-solidity.
Notice how `ERC721Mintable` has no parentheses because the argument list is 0.
This causes a compiler error.
Perhaps the parser could let us know that the modifier has empty parentheses would be enough (still not optimal but better than checking for an uppercase letter in the name).

**Comment by federicobond** [comment]
I see, would the problem be solved if I returned `arguments: null` for no parentheses and `arguments: []` in the other case?

**Comment by Janther** [comment]
I can work with that.

Thank you

**Comment by federicobond** [comment]
Just pushed https://github.com/federicobond/solidity-parser-antlr/commit/1099a16d3699c15ac0e63a050f61a45ccc9ff84f to master which addresses this issue. Let me know if it works.

**Comment by Janther** [comment]
it works :)
