### ISSUE TITLE
Parse left shift / right shift

### ISSUE THREAD

**Issue by cgewecke** [federicobond/solidity-parser-antlr#7]
Just one more:
```javascript
uint256 constant FIXED_ONE = uint256(1) << PRECISION;
```
errors with:
```javascript
{}
```

FWIW I ran Zeppelin, Melonport, Chronobank, Bancor, & Gnosis through the parser and issues 5,6,7 are the only things that came up. Looks good!

**Comment by federicobond** [comment]
Just published a new version (0.1.0) with these issues fixed.

**Comment by cgewecke** [comment]
Thanks!
