### ISSUE TITLE
ImportDeclaration type definition missing

### ISSUE THREAD

**Issue by andremedeiros** [federicobond/solidity-parser-antlr#70]
`ImportDeclaration` is defined as a type, but it's missing a declaration.

**Comment by federicobond** [comment]
Hi, thanks for reporting this. Would you be able to submit a PR fixing this?

**Comment by andremedeiros** [comment]
Oh, absolutely!

**Comment by andremedeiros** [comment]
Fixed that issue, and also submitted a PR fixing another small one.
