### ISSUE TITLE
Augment the `Parameter` type

### ISSUE THREAD

**Issue by andremedeiros** [federicobond/solidity-parser-antlr#74]
This isn't as much a request, but it's more for me to track (PR will be incoming.)

Basically, the `Parameter` type, as defined [here](https://github.com/federicobond/solidity-parser-antlr/blob/master/index.d.ts#L172-L178) should be more of an alias, as it's really not represented in the AST like this.

For instance, to represent an event declaration node, you would use something like this:

```typescript
const EVENT_NODE = {
  name: "__StatementCoverage",
  parameters: {
    parameters: [
      {
        name: "value",
        type: "VariableDeclaration",
        typeName: { name: "uint32", type: "ElementaryTypeName" },
      },
    ],
    type: "ParameterList",
  },
  type: "EventDefinition",
};
```

If you type `EVENT_NODE` as `EventDefinition`, the type checker will fail because `parameters` can only contain `type: Parameter` children.

**Comment by federicobond** [comment]
Yes, in fact `Parameter` is one of those nodes added to the type definition that are not present in the AST. It should be replaced by the actual node types returned in that case.

**Comment by andremedeiros** [comment]
Seems like I was mistaken. ParameterList can contain type `Parameter` or type `VariableDeclaration`.

So far what I have is:

```
type: "Parameter" | "VariableDeclaration";
typeName: ArrayTypeName | ElementaryTypeName; // should be easy to find these
name: string;
storageLocation: null; // (need to figure this one out)
isStateVar: bool;
isIndexed: bool;
```

Expect a PR tonight or tomorrow am.
