### ISSUE TITLE
Parse error when using underscores in numbers

### ISSUE THREAD

**Issue by cgewecke** [federicobond/solidity-parser-antlr#79]
(Originally reported in [solidity-coverage 321](https://github.com/sc-forks/solidity-coverage/issues/321))

This compiles on remix (solc 0.5.10) ...
```solidity
pragma solidity >=0.4.22 <0.6.0;

contract Test {
    uint public x = 1_000_000;
}
```

.. but the parser throws with:
```
ParserError: extraneous input '_000_000' expecting ';'
```

[Natural language description](https://github.com/ethereum/solidity/pull/4684/files#diff-64a4841069b13331da3813eb44e736b4) of the rule at the PR which introduced this syntax.

:wave: Hi @federicobond

**Comment by federicobond** [comment]
Hi @cgewecke, nice to see you again! I just pushed a fix to the project, can you test with latest master?

**Comment by cgewecke** [comment]
@federicobond Yes works! Thank you.

**Comment by cgewecke** [comment]
@federicobond, Apologies, I didn't test this fix thoroughly enough. Have found it's throwing an error in a [zeppelin contract](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/crowdsale/distribution/RefundableCrowdsale.sol#L63-L74) at this function:
```solidity
function _finalization() internal {
    if (goalReached()) {
        _escrow.close();
        _escrow.beneficiaryWithdraw();
    } else {
        _escrow.enableRefunds();
    }

    super._finalization();
}
```

Error is:
```
ParserError: no viable alternative at input 'super._' (73:13)
```

This is the change.
```diff
-  : ([0-9]+ | ([0-9]* '.' [0-9]+) ) ( [eE] [0-9]+ )? ;
+  : ([0-9] ( '_'? [0-9])* | ([0-9_]* '.' [0-9_]+) ) ( [eE] [0-9_]+ )? ;
```

**Comment by federicobond** [comment]
Can you check now with `master`?

**Comment by cgewecke** [comment]
@federicobond Yes, that works, thanks so much. It's passing a [Zeppelin E2E](https://circleci.com/gh/sc-forks/solidity-coverage/720) on my side.

**Comment by federicobond** [comment]
Great, a release should follow up soon.
